/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetSolCollectionTraitsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSolCollectionTraitsRequest{}

// GetSolCollectionTraitsRequest struct for GetSolCollectionTraitsRequest
type GetSolCollectionTraitsRequest struct {
	// The tag of the collection.
	CollectionTag *string `json:"collection_tag,omitempty"`
}

// NewGetSolCollectionTraitsRequest instantiates a new GetSolCollectionTraitsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSolCollectionTraitsRequest() *GetSolCollectionTraitsRequest {
	this := GetSolCollectionTraitsRequest{}
	return &this
}

// NewGetSolCollectionTraitsRequestWithDefaults instantiates a new GetSolCollectionTraitsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSolCollectionTraitsRequestWithDefaults() *GetSolCollectionTraitsRequest {
	this := GetSolCollectionTraitsRequest{}
	return &this
}

// GetCollectionTag returns the CollectionTag field value if set, zero value otherwise.
func (o *GetSolCollectionTraitsRequest) GetCollectionTag() string {
	if o == nil || isNil(o.CollectionTag) {
		var ret string
		return ret
	}
	return *o.CollectionTag
}

// GetCollectionTagOk returns a tuple with the CollectionTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSolCollectionTraitsRequest) GetCollectionTagOk() (*string, bool) {
	if o == nil || isNil(o.CollectionTag) {
		return nil, false
	}
	return o.CollectionTag, true
}

// HasCollectionTag returns a boolean if a field has been set.
func (o *GetSolCollectionTraitsRequest) HasCollectionTag() bool {
	if o != nil && !isNil(o.CollectionTag) {
		return true
	}

	return false
}

// SetCollectionTag gets a reference to the given string and assigns it to the CollectionTag field.
func (o *GetSolCollectionTraitsRequest) SetCollectionTag(v string) {
	o.CollectionTag = &v
}

func (o GetSolCollectionTraitsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSolCollectionTraitsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.CollectionTag) {
		toSerialize["collection_tag"] = o.CollectionTag
	}
	return toSerialize, nil
}

type NullableGetSolCollectionTraitsRequest struct {
	value *GetSolCollectionTraitsRequest
	isSet bool
}

func (v NullableGetSolCollectionTraitsRequest) Get() *GetSolCollectionTraitsRequest {
	return v.value
}

func (v *NullableGetSolCollectionTraitsRequest) Set(val *GetSolCollectionTraitsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSolCollectionTraitsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSolCollectionTraitsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSolCollectionTraitsRequest(val *GetSolCollectionTraitsRequest) *NullableGetSolCollectionTraitsRequest {
	return &NullableGetSolCollectionTraitsRequest{value: val, isSet: true}
}

func (v NullableGetSolCollectionTraitsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSolCollectionTraitsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


