/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetSolWashTradeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSolWashTradeRequest{}

// GetSolWashTradeRequest struct for GetSolWashTradeRequest
type GetSolWashTradeRequest struct {
	// The first signature to valildate.
	FirstSignature string `json:"first_signature"`
}

// NewGetSolWashTradeRequest instantiates a new GetSolWashTradeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSolWashTradeRequest(firstSignature string) *GetSolWashTradeRequest {
	this := GetSolWashTradeRequest{}
	this.FirstSignature = firstSignature
	return &this
}

// NewGetSolWashTradeRequestWithDefaults instantiates a new GetSolWashTradeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSolWashTradeRequestWithDefaults() *GetSolWashTradeRequest {
	this := GetSolWashTradeRequest{}
	return &this
}

// GetFirstSignature returns the FirstSignature field value
func (o *GetSolWashTradeRequest) GetFirstSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstSignature
}

// GetFirstSignatureOk returns a tuple with the FirstSignature field value
// and a boolean to check if the value has been set.
func (o *GetSolWashTradeRequest) GetFirstSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstSignature, true
}

// SetFirstSignature sets field value
func (o *GetSolWashTradeRequest) SetFirstSignature(v string) {
	o.FirstSignature = v
}

func (o GetSolWashTradeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSolWashTradeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["first_signature"] = o.FirstSignature
	return toSerialize, nil
}

type NullableGetSolWashTradeRequest struct {
	value *GetSolWashTradeRequest
	isSet bool
}

func (v NullableGetSolWashTradeRequest) Get() *GetSolWashTradeRequest {
	return v.value
}

func (v *NullableGetSolWashTradeRequest) Set(val *GetSolWashTradeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSolWashTradeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSolWashTradeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSolWashTradeRequest(val *GetSolWashTradeRequest) *NullableGetSolWashTradeRequest {
	return &NullableGetSolWashTradeRequest{value: val, isSet: true}
}

func (v NullableGetSolWashTradeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSolWashTradeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


