/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetSolTokenSummaryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSolTokenSummaryRequest{}

// GetSolTokenSummaryRequest struct for GetSolTokenSummaryRequest
type GetSolTokenSummaryRequest struct {
	// A token mint address or list of token addresses.
	MintAddress []string `json:"mint_address"`
	// The numerical id for the token. Provide either id or mint address.
	TokenId *string `json:"token_id,omitempty"`
	// The start date to pull data for calculations
	StartDate *string `json:"start_date,omitempty"`
	// The end date to pull data for calculations
	EndDate *string `json:"end_date,omitempty"`
	// The currency to report results in
	ReptCurr *string `json:"rept_curr,omitempty"`
	// Exclude suspected wash transactions?
	ExcludeWash *bool `json:"exclude_wash,omitempty"`
}

// NewGetSolTokenSummaryRequest instantiates a new GetSolTokenSummaryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSolTokenSummaryRequest(mintAddress []string) *GetSolTokenSummaryRequest {
	this := GetSolTokenSummaryRequest{}
	this.MintAddress = mintAddress
	return &this
}

// NewGetSolTokenSummaryRequestWithDefaults instantiates a new GetSolTokenSummaryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSolTokenSummaryRequestWithDefaults() *GetSolTokenSummaryRequest {
	this := GetSolTokenSummaryRequest{}
	return &this
}

// GetMintAddress returns the MintAddress field value
func (o *GetSolTokenSummaryRequest) GetMintAddress() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.MintAddress
}

// GetMintAddressOk returns a tuple with the MintAddress field value
// and a boolean to check if the value has been set.
func (o *GetSolTokenSummaryRequest) GetMintAddressOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MintAddress, true
}

// SetMintAddress sets field value
func (o *GetSolTokenSummaryRequest) SetMintAddress(v []string) {
	o.MintAddress = v
}

// GetTokenId returns the TokenId field value if set, zero value otherwise.
func (o *GetSolTokenSummaryRequest) GetTokenId() string {
	if o == nil || isNil(o.TokenId) {
		var ret string
		return ret
	}
	return *o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSolTokenSummaryRequest) GetTokenIdOk() (*string, bool) {
	if o == nil || isNil(o.TokenId) {
		return nil, false
	}
	return o.TokenId, true
}

// HasTokenId returns a boolean if a field has been set.
func (o *GetSolTokenSummaryRequest) HasTokenId() bool {
	if o != nil && !isNil(o.TokenId) {
		return true
	}

	return false
}

// SetTokenId gets a reference to the given string and assigns it to the TokenId field.
func (o *GetSolTokenSummaryRequest) SetTokenId(v string) {
	o.TokenId = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *GetSolTokenSummaryRequest) GetStartDate() string {
	if o == nil || isNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSolTokenSummaryRequest) GetStartDateOk() (*string, bool) {
	if o == nil || isNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *GetSolTokenSummaryRequest) HasStartDate() bool {
	if o != nil && !isNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *GetSolTokenSummaryRequest) SetStartDate(v string) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *GetSolTokenSummaryRequest) GetEndDate() string {
	if o == nil || isNil(o.EndDate) {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSolTokenSummaryRequest) GetEndDateOk() (*string, bool) {
	if o == nil || isNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *GetSolTokenSummaryRequest) HasEndDate() bool {
	if o != nil && !isNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *GetSolTokenSummaryRequest) SetEndDate(v string) {
	o.EndDate = &v
}

// GetReptCurr returns the ReptCurr field value if set, zero value otherwise.
func (o *GetSolTokenSummaryRequest) GetReptCurr() string {
	if o == nil || isNil(o.ReptCurr) {
		var ret string
		return ret
	}
	return *o.ReptCurr
}

// GetReptCurrOk returns a tuple with the ReptCurr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSolTokenSummaryRequest) GetReptCurrOk() (*string, bool) {
	if o == nil || isNil(o.ReptCurr) {
		return nil, false
	}
	return o.ReptCurr, true
}

// HasReptCurr returns a boolean if a field has been set.
func (o *GetSolTokenSummaryRequest) HasReptCurr() bool {
	if o != nil && !isNil(o.ReptCurr) {
		return true
	}

	return false
}

// SetReptCurr gets a reference to the given string and assigns it to the ReptCurr field.
func (o *GetSolTokenSummaryRequest) SetReptCurr(v string) {
	o.ReptCurr = &v
}

// GetExcludeWash returns the ExcludeWash field value if set, zero value otherwise.
func (o *GetSolTokenSummaryRequest) GetExcludeWash() bool {
	if o == nil || isNil(o.ExcludeWash) {
		var ret bool
		return ret
	}
	return *o.ExcludeWash
}

// GetExcludeWashOk returns a tuple with the ExcludeWash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSolTokenSummaryRequest) GetExcludeWashOk() (*bool, bool) {
	if o == nil || isNil(o.ExcludeWash) {
		return nil, false
	}
	return o.ExcludeWash, true
}

// HasExcludeWash returns a boolean if a field has been set.
func (o *GetSolTokenSummaryRequest) HasExcludeWash() bool {
	if o != nil && !isNil(o.ExcludeWash) {
		return true
	}

	return false
}

// SetExcludeWash gets a reference to the given bool and assigns it to the ExcludeWash field.
func (o *GetSolTokenSummaryRequest) SetExcludeWash(v bool) {
	o.ExcludeWash = &v
}

func (o GetSolTokenSummaryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSolTokenSummaryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mint_address"] = o.MintAddress
	if !isNil(o.TokenId) {
		toSerialize["token_id"] = o.TokenId
	}
	if !isNil(o.StartDate) {
		toSerialize["start_date"] = o.StartDate
	}
	if !isNil(o.EndDate) {
		toSerialize["end_date"] = o.EndDate
	}
	if !isNil(o.ReptCurr) {
		toSerialize["rept_curr"] = o.ReptCurr
	}
	if !isNil(o.ExcludeWash) {
		toSerialize["exclude_wash"] = o.ExcludeWash
	}
	return toSerialize, nil
}

type NullableGetSolTokenSummaryRequest struct {
	value *GetSolTokenSummaryRequest
	isSet bool
}

func (v NullableGetSolTokenSummaryRequest) Get() *GetSolTokenSummaryRequest {
	return v.value
}

func (v *NullableGetSolTokenSummaryRequest) Set(val *GetSolTokenSummaryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSolTokenSummaryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSolTokenSummaryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSolTokenSummaryRequest(val *GetSolTokenSummaryRequest) *NullableGetSolTokenSummaryRequest {
	return &NullableGetSolTokenSummaryRequest{value: val, isSet: true}
}

func (v NullableGetSolTokenSummaryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSolTokenSummaryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


