/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetPolCollectionOwnersRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPolCollectionOwnersRequest{}

// GetPolCollectionOwnersRequest struct for GetPolCollectionOwnersRequest
type GetPolCollectionOwnersRequest struct {
	// The contract address of the collection.
	CollectionAddress string `json:"collection_address"`
	// The pagination cursor.
	Page *int32 `json:"page,omitempty"`
	// The number of records returned per page.
	PageSize *int32 `json:"page_size,omitempty"`
}

// NewGetPolCollectionOwnersRequest instantiates a new GetPolCollectionOwnersRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPolCollectionOwnersRequest(collectionAddress string) *GetPolCollectionOwnersRequest {
	this := GetPolCollectionOwnersRequest{}
	this.CollectionAddress = collectionAddress
	return &this
}

// NewGetPolCollectionOwnersRequestWithDefaults instantiates a new GetPolCollectionOwnersRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPolCollectionOwnersRequestWithDefaults() *GetPolCollectionOwnersRequest {
	this := GetPolCollectionOwnersRequest{}
	return &this
}

// GetCollectionAddress returns the CollectionAddress field value
func (o *GetPolCollectionOwnersRequest) GetCollectionAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CollectionAddress
}

// GetCollectionAddressOk returns a tuple with the CollectionAddress field value
// and a boolean to check if the value has been set.
func (o *GetPolCollectionOwnersRequest) GetCollectionAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CollectionAddress, true
}

// SetCollectionAddress sets field value
func (o *GetPolCollectionOwnersRequest) SetCollectionAddress(v string) {
	o.CollectionAddress = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *GetPolCollectionOwnersRequest) GetPage() int32 {
	if o == nil || isNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPolCollectionOwnersRequest) GetPageOk() (*int32, bool) {
	if o == nil || isNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *GetPolCollectionOwnersRequest) HasPage() bool {
	if o != nil && !isNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *GetPolCollectionOwnersRequest) SetPage(v int32) {
	o.Page = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *GetPolCollectionOwnersRequest) GetPageSize() int32 {
	if o == nil || isNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPolCollectionOwnersRequest) GetPageSizeOk() (*int32, bool) {
	if o == nil || isNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *GetPolCollectionOwnersRequest) HasPageSize() bool {
	if o != nil && !isNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *GetPolCollectionOwnersRequest) SetPageSize(v int32) {
	o.PageSize = &v
}

func (o GetPolCollectionOwnersRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPolCollectionOwnersRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["collection_address"] = o.CollectionAddress
	if !isNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !isNil(o.PageSize) {
		toSerialize["page_size"] = o.PageSize
	}
	return toSerialize, nil
}

type NullableGetPolCollectionOwnersRequest struct {
	value *GetPolCollectionOwnersRequest
	isSet bool
}

func (v NullableGetPolCollectionOwnersRequest) Get() *GetPolCollectionOwnersRequest {
	return v.value
}

func (v *NullableGetPolCollectionOwnersRequest) Set(val *GetPolCollectionOwnersRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPolCollectionOwnersRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPolCollectionOwnersRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPolCollectionOwnersRequest(val *GetPolCollectionOwnersRequest) *NullableGetPolCollectionOwnersRequest {
	return &NullableGetPolCollectionOwnersRequest{value: val, isSet: true}
}

func (v NullableGetPolCollectionOwnersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPolCollectionOwnersRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


