/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetEthCollectionsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEthCollectionsRequest{}

// GetEthCollectionsRequest struct for GetEthCollectionsRequest
type GetEthCollectionsRequest struct {
	// The pagination cursor.
	Page *int32 `json:"page,omitempty"`
	// The number of records returned per page.
	PageSize *int32 `json:"page_size,omitempty"`
	// The name of the collection searched.
	CollectionName *string `json:"collection_name,omitempty"`
	// Only return collections that have traded.
	Traded *bool `json:"traded,omitempty"`
	// Only return collections recorded after this day [YYYY-MM-DD]
	CreatedAfter *string `json:"created_after,omitempty"`
	// The value to sort by. Defaults to created_at
	SortBy *string `json:"sort_by,omitempty"`
}

// NewGetEthCollectionsRequest instantiates a new GetEthCollectionsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEthCollectionsRequest() *GetEthCollectionsRequest {
	this := GetEthCollectionsRequest{}
	return &this
}

// NewGetEthCollectionsRequestWithDefaults instantiates a new GetEthCollectionsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEthCollectionsRequestWithDefaults() *GetEthCollectionsRequest {
	this := GetEthCollectionsRequest{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *GetEthCollectionsRequest) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthCollectionsRequest) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *GetEthCollectionsRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *GetEthCollectionsRequest) SetPage(v int32) {
	o.Page = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *GetEthCollectionsRequest) GetPageSize() int32 {
	if o == nil || IsNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthCollectionsRequest) GetPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *GetEthCollectionsRequest) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *GetEthCollectionsRequest) SetPageSize(v int32) {
	o.PageSize = &v
}

// GetCollectionName returns the CollectionName field value if set, zero value otherwise.
func (o *GetEthCollectionsRequest) GetCollectionName() string {
	if o == nil || IsNil(o.CollectionName) {
		var ret string
		return ret
	}
	return *o.CollectionName
}

// GetCollectionNameOk returns a tuple with the CollectionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthCollectionsRequest) GetCollectionNameOk() (*string, bool) {
	if o == nil || IsNil(o.CollectionName) {
		return nil, false
	}
	return o.CollectionName, true
}

// HasCollectionName returns a boolean if a field has been set.
func (o *GetEthCollectionsRequest) HasCollectionName() bool {
	if o != nil && !IsNil(o.CollectionName) {
		return true
	}

	return false
}

// SetCollectionName gets a reference to the given string and assigns it to the CollectionName field.
func (o *GetEthCollectionsRequest) SetCollectionName(v string) {
	o.CollectionName = &v
}

// GetTraded returns the Traded field value if set, zero value otherwise.
func (o *GetEthCollectionsRequest) GetTraded() bool {
	if o == nil || IsNil(o.Traded) {
		var ret bool
		return ret
	}
	return *o.Traded
}

// GetTradedOk returns a tuple with the Traded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthCollectionsRequest) GetTradedOk() (*bool, bool) {
	if o == nil || IsNil(o.Traded) {
		return nil, false
	}
	return o.Traded, true
}

// HasTraded returns a boolean if a field has been set.
func (o *GetEthCollectionsRequest) HasTraded() bool {
	if o != nil && !IsNil(o.Traded) {
		return true
	}

	return false
}

// SetTraded gets a reference to the given bool and assigns it to the Traded field.
func (o *GetEthCollectionsRequest) SetTraded(v bool) {
	o.Traded = &v
}

// GetCreatedAfter returns the CreatedAfter field value if set, zero value otherwise.
func (o *GetEthCollectionsRequest) GetCreatedAfter() string {
	if o == nil || IsNil(o.CreatedAfter) {
		var ret string
		return ret
	}
	return *o.CreatedAfter
}

// GetCreatedAfterOk returns a tuple with the CreatedAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthCollectionsRequest) GetCreatedAfterOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAfter) {
		return nil, false
	}
	return o.CreatedAfter, true
}

// HasCreatedAfter returns a boolean if a field has been set.
func (o *GetEthCollectionsRequest) HasCreatedAfter() bool {
	if o != nil && !IsNil(o.CreatedAfter) {
		return true
	}

	return false
}

// SetCreatedAfter gets a reference to the given string and assigns it to the CreatedAfter field.
func (o *GetEthCollectionsRequest) SetCreatedAfter(v string) {
	o.CreatedAfter = &v
}

// GetSortBy returns the SortBy field value if set, zero value otherwise.
func (o *GetEthCollectionsRequest) GetSortBy() string {
	if o == nil || IsNil(o.SortBy) {
		var ret string
		return ret
	}
	return *o.SortBy
}

// GetSortByOk returns a tuple with the SortBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthCollectionsRequest) GetSortByOk() (*string, bool) {
	if o == nil || IsNil(o.SortBy) {
		return nil, false
	}
	return o.SortBy, true
}

// HasSortBy returns a boolean if a field has been set.
func (o *GetEthCollectionsRequest) HasSortBy() bool {
	if o != nil && !IsNil(o.SortBy) {
		return true
	}

	return false
}

// SetSortBy gets a reference to the given string and assigns it to the SortBy field.
func (o *GetEthCollectionsRequest) SetSortBy(v string) {
	o.SortBy = &v
}

func (o GetEthCollectionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEthCollectionsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PageSize) {
		toSerialize["page_size"] = o.PageSize
	}
	if !IsNil(o.CollectionName) {
		toSerialize["collection_name"] = o.CollectionName
	}
	if !IsNil(o.Traded) {
		toSerialize["traded"] = o.Traded
	}
	if !IsNil(o.CreatedAfter) {
		toSerialize["created_after"] = o.CreatedAfter
	}
	if !IsNil(o.SortBy) {
		toSerialize["sort_by"] = o.SortBy
	}
	return toSerialize, nil
}

type NullableGetEthCollectionsRequest struct {
	value *GetEthCollectionsRequest
	isSet bool
}

func (v NullableGetEthCollectionsRequest) Get() *GetEthCollectionsRequest {
	return v.value
}

func (v *NullableGetEthCollectionsRequest) Set(val *GetEthCollectionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEthCollectionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEthCollectionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEthCollectionsRequest(val *GetEthCollectionsRequest) *NullableGetEthCollectionsRequest {
	return &NullableGetEthCollectionsRequest{value: val, isSet: true}
}

func (v NullableGetEthCollectionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEthCollectionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


