/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetSolDefaultTokenRiskRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSolDefaultTokenRiskRequest{}

// GetSolDefaultTokenRiskRequest struct for GetSolDefaultTokenRiskRequest
type GetSolDefaultTokenRiskRequest struct {
	// A token mint address or list of mint addresses.
	MintAddress []string `json:"mint_address"`
	// The holding period to evaluate risk for, e.g. '12M'
	HoldingPeriod string `json:"holding_period"`
	// The currency to report results in
	ReptCurr *string `json:"rept_curr,omitempty"`
	// If true, report drawdown volatility (based on negative returns only).
	Drawdown *bool `json:"drawdown,omitempty"`
}

// NewGetSolDefaultTokenRiskRequest instantiates a new GetSolDefaultTokenRiskRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSolDefaultTokenRiskRequest(mintAddress []string, holdingPeriod string) *GetSolDefaultTokenRiskRequest {
	this := GetSolDefaultTokenRiskRequest{}
	this.MintAddress = mintAddress
	this.HoldingPeriod = holdingPeriod
	return &this
}

// NewGetSolDefaultTokenRiskRequestWithDefaults instantiates a new GetSolDefaultTokenRiskRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSolDefaultTokenRiskRequestWithDefaults() *GetSolDefaultTokenRiskRequest {
	this := GetSolDefaultTokenRiskRequest{}
	return &this
}

// GetMintAddress returns the MintAddress field value
func (o *GetSolDefaultTokenRiskRequest) GetMintAddress() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.MintAddress
}

// GetMintAddressOk returns a tuple with the MintAddress field value
// and a boolean to check if the value has been set.
func (o *GetSolDefaultTokenRiskRequest) GetMintAddressOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MintAddress, true
}

// SetMintAddress sets field value
func (o *GetSolDefaultTokenRiskRequest) SetMintAddress(v []string) {
	o.MintAddress = v
}

// GetHoldingPeriod returns the HoldingPeriod field value
func (o *GetSolDefaultTokenRiskRequest) GetHoldingPeriod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HoldingPeriod
}

// GetHoldingPeriodOk returns a tuple with the HoldingPeriod field value
// and a boolean to check if the value has been set.
func (o *GetSolDefaultTokenRiskRequest) GetHoldingPeriodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HoldingPeriod, true
}

// SetHoldingPeriod sets field value
func (o *GetSolDefaultTokenRiskRequest) SetHoldingPeriod(v string) {
	o.HoldingPeriod = v
}

// GetReptCurr returns the ReptCurr field value if set, zero value otherwise.
func (o *GetSolDefaultTokenRiskRequest) GetReptCurr() string {
	if o == nil || IsNil(o.ReptCurr) {
		var ret string
		return ret
	}
	return *o.ReptCurr
}

// GetReptCurrOk returns a tuple with the ReptCurr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSolDefaultTokenRiskRequest) GetReptCurrOk() (*string, bool) {
	if o == nil || IsNil(o.ReptCurr) {
		return nil, false
	}
	return o.ReptCurr, true
}

// HasReptCurr returns a boolean if a field has been set.
func (o *GetSolDefaultTokenRiskRequest) HasReptCurr() bool {
	if o != nil && !IsNil(o.ReptCurr) {
		return true
	}

	return false
}

// SetReptCurr gets a reference to the given string and assigns it to the ReptCurr field.
func (o *GetSolDefaultTokenRiskRequest) SetReptCurr(v string) {
	o.ReptCurr = &v
}

// GetDrawdown returns the Drawdown field value if set, zero value otherwise.
func (o *GetSolDefaultTokenRiskRequest) GetDrawdown() bool {
	if o == nil || IsNil(o.Drawdown) {
		var ret bool
		return ret
	}
	return *o.Drawdown
}

// GetDrawdownOk returns a tuple with the Drawdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSolDefaultTokenRiskRequest) GetDrawdownOk() (*bool, bool) {
	if o == nil || IsNil(o.Drawdown) {
		return nil, false
	}
	return o.Drawdown, true
}

// HasDrawdown returns a boolean if a field has been set.
func (o *GetSolDefaultTokenRiskRequest) HasDrawdown() bool {
	if o != nil && !IsNil(o.Drawdown) {
		return true
	}

	return false
}

// SetDrawdown gets a reference to the given bool and assigns it to the Drawdown field.
func (o *GetSolDefaultTokenRiskRequest) SetDrawdown(v bool) {
	o.Drawdown = &v
}

func (o GetSolDefaultTokenRiskRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSolDefaultTokenRiskRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mint_address"] = o.MintAddress
	toSerialize["holding_period"] = o.HoldingPeriod
	if !IsNil(o.ReptCurr) {
		toSerialize["rept_curr"] = o.ReptCurr
	}
	if !IsNil(o.Drawdown) {
		toSerialize["drawdown"] = o.Drawdown
	}
	return toSerialize, nil
}

type NullableGetSolDefaultTokenRiskRequest struct {
	value *GetSolDefaultTokenRiskRequest
	isSet bool
}

func (v NullableGetSolDefaultTokenRiskRequest) Get() *GetSolDefaultTokenRiskRequest {
	return v.value
}

func (v *NullableGetSolDefaultTokenRiskRequest) Set(val *GetSolDefaultTokenRiskRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSolDefaultTokenRiskRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSolDefaultTokenRiskRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSolDefaultTokenRiskRequest(val *GetSolDefaultTokenRiskRequest) *NullableGetSolDefaultTokenRiskRequest {
	return &NullableGetSolDefaultTokenRiskRequest{value: val, isSet: true}
}

func (v NullableGetSolDefaultTokenRiskRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSolDefaultTokenRiskRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


