/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetEthDefaultCollectionRiskRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEthDefaultCollectionRiskRequest{}

// GetEthDefaultCollectionRiskRequest struct for GetEthDefaultCollectionRiskRequest
type GetEthDefaultCollectionRiskRequest struct {
	// The contract address of the token collection.
	CollectionAddress string `json:"collection_address"`
	// The holding period to evaluate risk for, e.g. '12M'
	HoldingPeriod string `json:"holding_period"`
	// The currency to report results in
	ReptCurr *string `json:"rept_curr,omitempty"`
	// The amount of tokens in your portfolio
	Amount *int32 `json:"amount,omitempty"`
	// If true, report drawdown volatility (based on negative returns only).
	Drawdown *bool `json:"drawdown,omitempty"`
}

// NewGetEthDefaultCollectionRiskRequest instantiates a new GetEthDefaultCollectionRiskRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEthDefaultCollectionRiskRequest(collectionAddress string, holdingPeriod string) *GetEthDefaultCollectionRiskRequest {
	this := GetEthDefaultCollectionRiskRequest{}
	this.CollectionAddress = collectionAddress
	this.HoldingPeriod = holdingPeriod
	return &this
}

// NewGetEthDefaultCollectionRiskRequestWithDefaults instantiates a new GetEthDefaultCollectionRiskRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEthDefaultCollectionRiskRequestWithDefaults() *GetEthDefaultCollectionRiskRequest {
	this := GetEthDefaultCollectionRiskRequest{}
	return &this
}

// GetCollectionAddress returns the CollectionAddress field value
func (o *GetEthDefaultCollectionRiskRequest) GetCollectionAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CollectionAddress
}

// GetCollectionAddressOk returns a tuple with the CollectionAddress field value
// and a boolean to check if the value has been set.
func (o *GetEthDefaultCollectionRiskRequest) GetCollectionAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CollectionAddress, true
}

// SetCollectionAddress sets field value
func (o *GetEthDefaultCollectionRiskRequest) SetCollectionAddress(v string) {
	o.CollectionAddress = v
}

// GetHoldingPeriod returns the HoldingPeriod field value
func (o *GetEthDefaultCollectionRiskRequest) GetHoldingPeriod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HoldingPeriod
}

// GetHoldingPeriodOk returns a tuple with the HoldingPeriod field value
// and a boolean to check if the value has been set.
func (o *GetEthDefaultCollectionRiskRequest) GetHoldingPeriodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HoldingPeriod, true
}

// SetHoldingPeriod sets field value
func (o *GetEthDefaultCollectionRiskRequest) SetHoldingPeriod(v string) {
	o.HoldingPeriod = v
}

// GetReptCurr returns the ReptCurr field value if set, zero value otherwise.
func (o *GetEthDefaultCollectionRiskRequest) GetReptCurr() string {
	if o == nil || isNil(o.ReptCurr) {
		var ret string
		return ret
	}
	return *o.ReptCurr
}

// GetReptCurrOk returns a tuple with the ReptCurr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthDefaultCollectionRiskRequest) GetReptCurrOk() (*string, bool) {
	if o == nil || isNil(o.ReptCurr) {
		return nil, false
	}
	return o.ReptCurr, true
}

// HasReptCurr returns a boolean if a field has been set.
func (o *GetEthDefaultCollectionRiskRequest) HasReptCurr() bool {
	if o != nil && !isNil(o.ReptCurr) {
		return true
	}

	return false
}

// SetReptCurr gets a reference to the given string and assigns it to the ReptCurr field.
func (o *GetEthDefaultCollectionRiskRequest) SetReptCurr(v string) {
	o.ReptCurr = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *GetEthDefaultCollectionRiskRequest) GetAmount() int32 {
	if o == nil || isNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthDefaultCollectionRiskRequest) GetAmountOk() (*int32, bool) {
	if o == nil || isNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *GetEthDefaultCollectionRiskRequest) HasAmount() bool {
	if o != nil && !isNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *GetEthDefaultCollectionRiskRequest) SetAmount(v int32) {
	o.Amount = &v
}

// GetDrawdown returns the Drawdown field value if set, zero value otherwise.
func (o *GetEthDefaultCollectionRiskRequest) GetDrawdown() bool {
	if o == nil || isNil(o.Drawdown) {
		var ret bool
		return ret
	}
	return *o.Drawdown
}

// GetDrawdownOk returns a tuple with the Drawdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthDefaultCollectionRiskRequest) GetDrawdownOk() (*bool, bool) {
	if o == nil || isNil(o.Drawdown) {
		return nil, false
	}
	return o.Drawdown, true
}

// HasDrawdown returns a boolean if a field has been set.
func (o *GetEthDefaultCollectionRiskRequest) HasDrawdown() bool {
	if o != nil && !isNil(o.Drawdown) {
		return true
	}

	return false
}

// SetDrawdown gets a reference to the given bool and assigns it to the Drawdown field.
func (o *GetEthDefaultCollectionRiskRequest) SetDrawdown(v bool) {
	o.Drawdown = &v
}

func (o GetEthDefaultCollectionRiskRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEthDefaultCollectionRiskRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["collection_address"] = o.CollectionAddress
	toSerialize["holding_period"] = o.HoldingPeriod
	if !isNil(o.ReptCurr) {
		toSerialize["rept_curr"] = o.ReptCurr
	}
	if !isNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !isNil(o.Drawdown) {
		toSerialize["drawdown"] = o.Drawdown
	}
	return toSerialize, nil
}

type NullableGetEthDefaultCollectionRiskRequest struct {
	value *GetEthDefaultCollectionRiskRequest
	isSet bool
}

func (v NullableGetEthDefaultCollectionRiskRequest) Get() *GetEthDefaultCollectionRiskRequest {
	return v.value
}

func (v *NullableGetEthDefaultCollectionRiskRequest) Set(val *GetEthDefaultCollectionRiskRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEthDefaultCollectionRiskRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEthDefaultCollectionRiskRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEthDefaultCollectionRiskRequest(val *GetEthDefaultCollectionRiskRequest) *NullableGetEthDefaultCollectionRiskRequest {
	return &NullableGetEthDefaultCollectionRiskRequest{value: val, isSet: true}
}

func (v NullableGetEthDefaultCollectionRiskRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEthDefaultCollectionRiskRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


