/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetEthTokenAppraisalRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEthTokenAppraisalRequest{}

// GetEthTokenAppraisalRequest struct for GetEthTokenAppraisalRequest
type GetEthTokenAppraisalRequest struct {
	// The contract address of the token collection.
	CollectionAddress string `json:"collection_address"`
	// The id(s) for the token(s).
	TokenId []string `json:"token_id"`
	// The currency to report results in
	ReptCurr *string `json:"rept_curr,omitempty"`
	// The interval at which to calculate intermediate results and forecasts.
	Frequency *string `json:"frequency,omitempty"`
	// The forecast horizon (i.e. the number of periods to forecast out). Defaults to zero which only returns nowcasts.
	Horizon *int32 `json:"horizon,omitempty"`
	// The significance level for the liquidation estimate, e.g. 0.05 for 95% confidence
	Alpha *float32 `json:"alpha,omitempty"`
	// Exclude suspected wash transactions?
	ExcludeWash *bool `json:"exclude_wash,omitempty"`
}

// NewGetEthTokenAppraisalRequest instantiates a new GetEthTokenAppraisalRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEthTokenAppraisalRequest(collectionAddress string, tokenId []string) *GetEthTokenAppraisalRequest {
	this := GetEthTokenAppraisalRequest{}
	this.CollectionAddress = collectionAddress
	this.TokenId = tokenId
	return &this
}

// NewGetEthTokenAppraisalRequestWithDefaults instantiates a new GetEthTokenAppraisalRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEthTokenAppraisalRequestWithDefaults() *GetEthTokenAppraisalRequest {
	this := GetEthTokenAppraisalRequest{}
	return &this
}

// GetCollectionAddress returns the CollectionAddress field value
func (o *GetEthTokenAppraisalRequest) GetCollectionAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CollectionAddress
}

// GetCollectionAddressOk returns a tuple with the CollectionAddress field value
// and a boolean to check if the value has been set.
func (o *GetEthTokenAppraisalRequest) GetCollectionAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CollectionAddress, true
}

// SetCollectionAddress sets field value
func (o *GetEthTokenAppraisalRequest) SetCollectionAddress(v string) {
	o.CollectionAddress = v
}

// GetTokenId returns the TokenId field value
func (o *GetEthTokenAppraisalRequest) GetTokenId() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *GetEthTokenAppraisalRequest) GetTokenIdOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TokenId, true
}

// SetTokenId sets field value
func (o *GetEthTokenAppraisalRequest) SetTokenId(v []string) {
	o.TokenId = v
}

// GetReptCurr returns the ReptCurr field value if set, zero value otherwise.
func (o *GetEthTokenAppraisalRequest) GetReptCurr() string {
	if o == nil || IsNil(o.ReptCurr) {
		var ret string
		return ret
	}
	return *o.ReptCurr
}

// GetReptCurrOk returns a tuple with the ReptCurr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthTokenAppraisalRequest) GetReptCurrOk() (*string, bool) {
	if o == nil || IsNil(o.ReptCurr) {
		return nil, false
	}
	return o.ReptCurr, true
}

// HasReptCurr returns a boolean if a field has been set.
func (o *GetEthTokenAppraisalRequest) HasReptCurr() bool {
	if o != nil && !IsNil(o.ReptCurr) {
		return true
	}

	return false
}

// SetReptCurr gets a reference to the given string and assigns it to the ReptCurr field.
func (o *GetEthTokenAppraisalRequest) SetReptCurr(v string) {
	o.ReptCurr = &v
}

// GetFrequency returns the Frequency field value if set, zero value otherwise.
func (o *GetEthTokenAppraisalRequest) GetFrequency() string {
	if o == nil || IsNil(o.Frequency) {
		var ret string
		return ret
	}
	return *o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthTokenAppraisalRequest) GetFrequencyOk() (*string, bool) {
	if o == nil || IsNil(o.Frequency) {
		return nil, false
	}
	return o.Frequency, true
}

// HasFrequency returns a boolean if a field has been set.
func (o *GetEthTokenAppraisalRequest) HasFrequency() bool {
	if o != nil && !IsNil(o.Frequency) {
		return true
	}

	return false
}

// SetFrequency gets a reference to the given string and assigns it to the Frequency field.
func (o *GetEthTokenAppraisalRequest) SetFrequency(v string) {
	o.Frequency = &v
}

// GetHorizon returns the Horizon field value if set, zero value otherwise.
func (o *GetEthTokenAppraisalRequest) GetHorizon() int32 {
	if o == nil || IsNil(o.Horizon) {
		var ret int32
		return ret
	}
	return *o.Horizon
}

// GetHorizonOk returns a tuple with the Horizon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthTokenAppraisalRequest) GetHorizonOk() (*int32, bool) {
	if o == nil || IsNil(o.Horizon) {
		return nil, false
	}
	return o.Horizon, true
}

// HasHorizon returns a boolean if a field has been set.
func (o *GetEthTokenAppraisalRequest) HasHorizon() bool {
	if o != nil && !IsNil(o.Horizon) {
		return true
	}

	return false
}

// SetHorizon gets a reference to the given int32 and assigns it to the Horizon field.
func (o *GetEthTokenAppraisalRequest) SetHorizon(v int32) {
	o.Horizon = &v
}

// GetAlpha returns the Alpha field value if set, zero value otherwise.
func (o *GetEthTokenAppraisalRequest) GetAlpha() float32 {
	if o == nil || IsNil(o.Alpha) {
		var ret float32
		return ret
	}
	return *o.Alpha
}

// GetAlphaOk returns a tuple with the Alpha field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthTokenAppraisalRequest) GetAlphaOk() (*float32, bool) {
	if o == nil || IsNil(o.Alpha) {
		return nil, false
	}
	return o.Alpha, true
}

// HasAlpha returns a boolean if a field has been set.
func (o *GetEthTokenAppraisalRequest) HasAlpha() bool {
	if o != nil && !IsNil(o.Alpha) {
		return true
	}

	return false
}

// SetAlpha gets a reference to the given float32 and assigns it to the Alpha field.
func (o *GetEthTokenAppraisalRequest) SetAlpha(v float32) {
	o.Alpha = &v
}

// GetExcludeWash returns the ExcludeWash field value if set, zero value otherwise.
func (o *GetEthTokenAppraisalRequest) GetExcludeWash() bool {
	if o == nil || IsNil(o.ExcludeWash) {
		var ret bool
		return ret
	}
	return *o.ExcludeWash
}

// GetExcludeWashOk returns a tuple with the ExcludeWash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthTokenAppraisalRequest) GetExcludeWashOk() (*bool, bool) {
	if o == nil || IsNil(o.ExcludeWash) {
		return nil, false
	}
	return o.ExcludeWash, true
}

// HasExcludeWash returns a boolean if a field has been set.
func (o *GetEthTokenAppraisalRequest) HasExcludeWash() bool {
	if o != nil && !IsNil(o.ExcludeWash) {
		return true
	}

	return false
}

// SetExcludeWash gets a reference to the given bool and assigns it to the ExcludeWash field.
func (o *GetEthTokenAppraisalRequest) SetExcludeWash(v bool) {
	o.ExcludeWash = &v
}

func (o GetEthTokenAppraisalRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEthTokenAppraisalRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["collection_address"] = o.CollectionAddress
	toSerialize["token_id"] = o.TokenId
	if !IsNil(o.ReptCurr) {
		toSerialize["rept_curr"] = o.ReptCurr
	}
	if !IsNil(o.Frequency) {
		toSerialize["frequency"] = o.Frequency
	}
	if !IsNil(o.Horizon) {
		toSerialize["horizon"] = o.Horizon
	}
	if !IsNil(o.Alpha) {
		toSerialize["alpha"] = o.Alpha
	}
	if !IsNil(o.ExcludeWash) {
		toSerialize["exclude_wash"] = o.ExcludeWash
	}
	return toSerialize, nil
}

type NullableGetEthTokenAppraisalRequest struct {
	value *GetEthTokenAppraisalRequest
	isSet bool
}

func (v NullableGetEthTokenAppraisalRequest) Get() *GetEthTokenAppraisalRequest {
	return v.value
}

func (v *NullableGetEthTokenAppraisalRequest) Set(val *GetEthTokenAppraisalRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEthTokenAppraisalRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEthTokenAppraisalRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEthTokenAppraisalRequest(val *GetEthTokenAppraisalRequest) *NullableGetEthTokenAppraisalRequest {
	return &NullableGetEthTokenAppraisalRequest{value: val, isSet: true}
}

func (v NullableGetEthTokenAppraisalRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEthTokenAppraisalRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


