/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetSolCollectionTransactionsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSolCollectionTransactionsRequest{}

// GetSolCollectionTransactionsRequest struct for GetSolCollectionTransactionsRequest
type GetSolCollectionTransactionsRequest struct {
	// The Gallop slug for the collection. Please see sol/getCollections endpoint.
	CollectionTag string `json:"collection_tag"`
	// The pagination cursor.
	Page *int32 `json:"page,omitempty"`
	// The number of records returned per page.
	PageSize *int32 `json:"page_size,omitempty"`
	// The earliest block timestamp.
	StartDate *string `json:"start_date,omitempty"`
	// The latest block timestamp.
	EndDate *string `json:"end_date,omitempty"`
}

// NewGetSolCollectionTransactionsRequest instantiates a new GetSolCollectionTransactionsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSolCollectionTransactionsRequest(collectionTag string) *GetSolCollectionTransactionsRequest {
	this := GetSolCollectionTransactionsRequest{}
	this.CollectionTag = collectionTag
	return &this
}

// NewGetSolCollectionTransactionsRequestWithDefaults instantiates a new GetSolCollectionTransactionsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSolCollectionTransactionsRequestWithDefaults() *GetSolCollectionTransactionsRequest {
	this := GetSolCollectionTransactionsRequest{}
	return &this
}

// GetCollectionTag returns the CollectionTag field value
func (o *GetSolCollectionTransactionsRequest) GetCollectionTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CollectionTag
}

// GetCollectionTagOk returns a tuple with the CollectionTag field value
// and a boolean to check if the value has been set.
func (o *GetSolCollectionTransactionsRequest) GetCollectionTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CollectionTag, true
}

// SetCollectionTag sets field value
func (o *GetSolCollectionTransactionsRequest) SetCollectionTag(v string) {
	o.CollectionTag = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *GetSolCollectionTransactionsRequest) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSolCollectionTransactionsRequest) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *GetSolCollectionTransactionsRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *GetSolCollectionTransactionsRequest) SetPage(v int32) {
	o.Page = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *GetSolCollectionTransactionsRequest) GetPageSize() int32 {
	if o == nil || IsNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSolCollectionTransactionsRequest) GetPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *GetSolCollectionTransactionsRequest) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *GetSolCollectionTransactionsRequest) SetPageSize(v int32) {
	o.PageSize = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *GetSolCollectionTransactionsRequest) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSolCollectionTransactionsRequest) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *GetSolCollectionTransactionsRequest) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *GetSolCollectionTransactionsRequest) SetStartDate(v string) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *GetSolCollectionTransactionsRequest) GetEndDate() string {
	if o == nil || IsNil(o.EndDate) {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSolCollectionTransactionsRequest) GetEndDateOk() (*string, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *GetSolCollectionTransactionsRequest) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *GetSolCollectionTransactionsRequest) SetEndDate(v string) {
	o.EndDate = &v
}

func (o GetSolCollectionTransactionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSolCollectionTransactionsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["collection_tag"] = o.CollectionTag
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PageSize) {
		toSerialize["page_size"] = o.PageSize
	}
	if !IsNil(o.StartDate) {
		toSerialize["start_date"] = o.StartDate
	}
	if !IsNil(o.EndDate) {
		toSerialize["end_date"] = o.EndDate
	}
	return toSerialize, nil
}

type NullableGetSolCollectionTransactionsRequest struct {
	value *GetSolCollectionTransactionsRequest
	isSet bool
}

func (v NullableGetSolCollectionTransactionsRequest) Get() *GetSolCollectionTransactionsRequest {
	return v.value
}

func (v *NullableGetSolCollectionTransactionsRequest) Set(val *GetSolCollectionTransactionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSolCollectionTransactionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSolCollectionTransactionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSolCollectionTransactionsRequest(val *GetSolCollectionTransactionsRequest) *NullableGetSolCollectionTransactionsRequest {
	return &NullableGetSolCollectionTransactionsRequest{value: val, isSet: true}
}

func (v NullableGetSolCollectionTransactionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSolCollectionTransactionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


