/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetSolTokenTransactionsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSolTokenTransactionsRequest{}

// GetSolTokenTransactionsRequest struct for GetSolTokenTransactionsRequest
type GetSolTokenTransactionsRequest struct {
	// The mint address of the token.
	MintAddress string `json:"mint_address"`
	// The pagination cursor.
	Page *int32 `json:"page,omitempty"`
	// The number of records returned per page.
	PageSize *int32 `json:"page_size,omitempty"`
	// The earliest block timestamp.
	StartDate *string `json:"start_date,omitempty"`
	// The latest block timestamp.
	EndDate *string `json:"end_date,omitempty"`
}

// NewGetSolTokenTransactionsRequest instantiates a new GetSolTokenTransactionsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSolTokenTransactionsRequest(mintAddress string) *GetSolTokenTransactionsRequest {
	this := GetSolTokenTransactionsRequest{}
	this.MintAddress = mintAddress
	return &this
}

// NewGetSolTokenTransactionsRequestWithDefaults instantiates a new GetSolTokenTransactionsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSolTokenTransactionsRequestWithDefaults() *GetSolTokenTransactionsRequest {
	this := GetSolTokenTransactionsRequest{}
	return &this
}

// GetMintAddress returns the MintAddress field value
func (o *GetSolTokenTransactionsRequest) GetMintAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MintAddress
}

// GetMintAddressOk returns a tuple with the MintAddress field value
// and a boolean to check if the value has been set.
func (o *GetSolTokenTransactionsRequest) GetMintAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MintAddress, true
}

// SetMintAddress sets field value
func (o *GetSolTokenTransactionsRequest) SetMintAddress(v string) {
	o.MintAddress = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *GetSolTokenTransactionsRequest) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSolTokenTransactionsRequest) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *GetSolTokenTransactionsRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *GetSolTokenTransactionsRequest) SetPage(v int32) {
	o.Page = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *GetSolTokenTransactionsRequest) GetPageSize() int32 {
	if o == nil || IsNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSolTokenTransactionsRequest) GetPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *GetSolTokenTransactionsRequest) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *GetSolTokenTransactionsRequest) SetPageSize(v int32) {
	o.PageSize = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *GetSolTokenTransactionsRequest) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSolTokenTransactionsRequest) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *GetSolTokenTransactionsRequest) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *GetSolTokenTransactionsRequest) SetStartDate(v string) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *GetSolTokenTransactionsRequest) GetEndDate() string {
	if o == nil || IsNil(o.EndDate) {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSolTokenTransactionsRequest) GetEndDateOk() (*string, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *GetSolTokenTransactionsRequest) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *GetSolTokenTransactionsRequest) SetEndDate(v string) {
	o.EndDate = &v
}

func (o GetSolTokenTransactionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSolTokenTransactionsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mint_address"] = o.MintAddress
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PageSize) {
		toSerialize["page_size"] = o.PageSize
	}
	if !IsNil(o.StartDate) {
		toSerialize["start_date"] = o.StartDate
	}
	if !IsNil(o.EndDate) {
		toSerialize["end_date"] = o.EndDate
	}
	return toSerialize, nil
}

type NullableGetSolTokenTransactionsRequest struct {
	value *GetSolTokenTransactionsRequest
	isSet bool
}

func (v NullableGetSolTokenTransactionsRequest) Get() *GetSolTokenTransactionsRequest {
	return v.value
}

func (v *NullableGetSolTokenTransactionsRequest) Set(val *GetSolTokenTransactionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSolTokenTransactionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSolTokenTransactionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSolTokenTransactionsRequest(val *GetSolTokenTransactionsRequest) *NullableGetSolTokenTransactionsRequest {
	return &NullableGetSolTokenTransactionsRequest{value: val, isSet: true}
}

func (v NullableGetSolTokenTransactionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSolTokenTransactionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


