/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetEthCollectionSalesOHLCRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEthCollectionSalesOHLCRequest{}

// GetEthCollectionSalesOHLCRequest struct for GetEthCollectionSalesOHLCRequest
type GetEthCollectionSalesOHLCRequest struct {
	// The Ethereum contract address to identify the collection.
	CollectionAddress string `json:"collection_address"`
	// The interval at which to return OHLC, e.g. `1D` for daily, `1M` for monthly etc.
	Frequency *string `json:"frequency,omitempty"`
	// An attribute of the NFT to group results by.
	GroupBy *string `json:"group_by,omitempty"`
	// If 'true', response dicts contain OHLCV
	Volume *bool `json:"volume,omitempty"`
	// If 'true', append number of trades to OHLC(V)
	NTrades *bool `json:"n_trades,omitempty"`
	// The currency to report results in
	ReptCurr *string `json:"rept_curr,omitempty"`
	// The start date to pull data for calculations
	StartDate *string `json:"start_date,omitempty"`
	// The end date to pull data for calculations
	EndDate *string `json:"end_date,omitempty"`
	// Exclude suspected wash transactions?
	ExcludeWash *bool `json:"exclude_wash,omitempty"`
}

// NewGetEthCollectionSalesOHLCRequest instantiates a new GetEthCollectionSalesOHLCRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEthCollectionSalesOHLCRequest(collectionAddress string) *GetEthCollectionSalesOHLCRequest {
	this := GetEthCollectionSalesOHLCRequest{}
	this.CollectionAddress = collectionAddress
	return &this
}

// NewGetEthCollectionSalesOHLCRequestWithDefaults instantiates a new GetEthCollectionSalesOHLCRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEthCollectionSalesOHLCRequestWithDefaults() *GetEthCollectionSalesOHLCRequest {
	this := GetEthCollectionSalesOHLCRequest{}
	return &this
}

// GetCollectionAddress returns the CollectionAddress field value
func (o *GetEthCollectionSalesOHLCRequest) GetCollectionAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CollectionAddress
}

// GetCollectionAddressOk returns a tuple with the CollectionAddress field value
// and a boolean to check if the value has been set.
func (o *GetEthCollectionSalesOHLCRequest) GetCollectionAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CollectionAddress, true
}

// SetCollectionAddress sets field value
func (o *GetEthCollectionSalesOHLCRequest) SetCollectionAddress(v string) {
	o.CollectionAddress = v
}

// GetFrequency returns the Frequency field value if set, zero value otherwise.
func (o *GetEthCollectionSalesOHLCRequest) GetFrequency() string {
	if o == nil || IsNil(o.Frequency) {
		var ret string
		return ret
	}
	return *o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthCollectionSalesOHLCRequest) GetFrequencyOk() (*string, bool) {
	if o == nil || IsNil(o.Frequency) {
		return nil, false
	}
	return o.Frequency, true
}

// HasFrequency returns a boolean if a field has been set.
func (o *GetEthCollectionSalesOHLCRequest) HasFrequency() bool {
	if o != nil && !IsNil(o.Frequency) {
		return true
	}

	return false
}

// SetFrequency gets a reference to the given string and assigns it to the Frequency field.
func (o *GetEthCollectionSalesOHLCRequest) SetFrequency(v string) {
	o.Frequency = &v
}

// GetGroupBy returns the GroupBy field value if set, zero value otherwise.
func (o *GetEthCollectionSalesOHLCRequest) GetGroupBy() string {
	if o == nil || IsNil(o.GroupBy) {
		var ret string
		return ret
	}
	return *o.GroupBy
}

// GetGroupByOk returns a tuple with the GroupBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthCollectionSalesOHLCRequest) GetGroupByOk() (*string, bool) {
	if o == nil || IsNil(o.GroupBy) {
		return nil, false
	}
	return o.GroupBy, true
}

// HasGroupBy returns a boolean if a field has been set.
func (o *GetEthCollectionSalesOHLCRequest) HasGroupBy() bool {
	if o != nil && !IsNil(o.GroupBy) {
		return true
	}

	return false
}

// SetGroupBy gets a reference to the given string and assigns it to the GroupBy field.
func (o *GetEthCollectionSalesOHLCRequest) SetGroupBy(v string) {
	o.GroupBy = &v
}

// GetVolume returns the Volume field value if set, zero value otherwise.
func (o *GetEthCollectionSalesOHLCRequest) GetVolume() bool {
	if o == nil || IsNil(o.Volume) {
		var ret bool
		return ret
	}
	return *o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthCollectionSalesOHLCRequest) GetVolumeOk() (*bool, bool) {
	if o == nil || IsNil(o.Volume) {
		return nil, false
	}
	return o.Volume, true
}

// HasVolume returns a boolean if a field has been set.
func (o *GetEthCollectionSalesOHLCRequest) HasVolume() bool {
	if o != nil && !IsNil(o.Volume) {
		return true
	}

	return false
}

// SetVolume gets a reference to the given bool and assigns it to the Volume field.
func (o *GetEthCollectionSalesOHLCRequest) SetVolume(v bool) {
	o.Volume = &v
}

// GetNTrades returns the NTrades field value if set, zero value otherwise.
func (o *GetEthCollectionSalesOHLCRequest) GetNTrades() bool {
	if o == nil || IsNil(o.NTrades) {
		var ret bool
		return ret
	}
	return *o.NTrades
}

// GetNTradesOk returns a tuple with the NTrades field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthCollectionSalesOHLCRequest) GetNTradesOk() (*bool, bool) {
	if o == nil || IsNil(o.NTrades) {
		return nil, false
	}
	return o.NTrades, true
}

// HasNTrades returns a boolean if a field has been set.
func (o *GetEthCollectionSalesOHLCRequest) HasNTrades() bool {
	if o != nil && !IsNil(o.NTrades) {
		return true
	}

	return false
}

// SetNTrades gets a reference to the given bool and assigns it to the NTrades field.
func (o *GetEthCollectionSalesOHLCRequest) SetNTrades(v bool) {
	o.NTrades = &v
}

// GetReptCurr returns the ReptCurr field value if set, zero value otherwise.
func (o *GetEthCollectionSalesOHLCRequest) GetReptCurr() string {
	if o == nil || IsNil(o.ReptCurr) {
		var ret string
		return ret
	}
	return *o.ReptCurr
}

// GetReptCurrOk returns a tuple with the ReptCurr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthCollectionSalesOHLCRequest) GetReptCurrOk() (*string, bool) {
	if o == nil || IsNil(o.ReptCurr) {
		return nil, false
	}
	return o.ReptCurr, true
}

// HasReptCurr returns a boolean if a field has been set.
func (o *GetEthCollectionSalesOHLCRequest) HasReptCurr() bool {
	if o != nil && !IsNil(o.ReptCurr) {
		return true
	}

	return false
}

// SetReptCurr gets a reference to the given string and assigns it to the ReptCurr field.
func (o *GetEthCollectionSalesOHLCRequest) SetReptCurr(v string) {
	o.ReptCurr = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *GetEthCollectionSalesOHLCRequest) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthCollectionSalesOHLCRequest) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *GetEthCollectionSalesOHLCRequest) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *GetEthCollectionSalesOHLCRequest) SetStartDate(v string) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *GetEthCollectionSalesOHLCRequest) GetEndDate() string {
	if o == nil || IsNil(o.EndDate) {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthCollectionSalesOHLCRequest) GetEndDateOk() (*string, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *GetEthCollectionSalesOHLCRequest) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *GetEthCollectionSalesOHLCRequest) SetEndDate(v string) {
	o.EndDate = &v
}

// GetExcludeWash returns the ExcludeWash field value if set, zero value otherwise.
func (o *GetEthCollectionSalesOHLCRequest) GetExcludeWash() bool {
	if o == nil || IsNil(o.ExcludeWash) {
		var ret bool
		return ret
	}
	return *o.ExcludeWash
}

// GetExcludeWashOk returns a tuple with the ExcludeWash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthCollectionSalesOHLCRequest) GetExcludeWashOk() (*bool, bool) {
	if o == nil || IsNil(o.ExcludeWash) {
		return nil, false
	}
	return o.ExcludeWash, true
}

// HasExcludeWash returns a boolean if a field has been set.
func (o *GetEthCollectionSalesOHLCRequest) HasExcludeWash() bool {
	if o != nil && !IsNil(o.ExcludeWash) {
		return true
	}

	return false
}

// SetExcludeWash gets a reference to the given bool and assigns it to the ExcludeWash field.
func (o *GetEthCollectionSalesOHLCRequest) SetExcludeWash(v bool) {
	o.ExcludeWash = &v
}

func (o GetEthCollectionSalesOHLCRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEthCollectionSalesOHLCRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["collection_address"] = o.CollectionAddress
	if !IsNil(o.Frequency) {
		toSerialize["frequency"] = o.Frequency
	}
	if !IsNil(o.GroupBy) {
		toSerialize["group_by"] = o.GroupBy
	}
	if !IsNil(o.Volume) {
		toSerialize["volume"] = o.Volume
	}
	if !IsNil(o.NTrades) {
		toSerialize["n_trades"] = o.NTrades
	}
	if !IsNil(o.ReptCurr) {
		toSerialize["rept_curr"] = o.ReptCurr
	}
	if !IsNil(o.StartDate) {
		toSerialize["start_date"] = o.StartDate
	}
	if !IsNil(o.EndDate) {
		toSerialize["end_date"] = o.EndDate
	}
	if !IsNil(o.ExcludeWash) {
		toSerialize["exclude_wash"] = o.ExcludeWash
	}
	return toSerialize, nil
}

type NullableGetEthCollectionSalesOHLCRequest struct {
	value *GetEthCollectionSalesOHLCRequest
	isSet bool
}

func (v NullableGetEthCollectionSalesOHLCRequest) Get() *GetEthCollectionSalesOHLCRequest {
	return v.value
}

func (v *NullableGetEthCollectionSalesOHLCRequest) Set(val *GetEthCollectionSalesOHLCRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEthCollectionSalesOHLCRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEthCollectionSalesOHLCRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEthCollectionSalesOHLCRequest(val *GetEthCollectionSalesOHLCRequest) *NullableGetEthCollectionSalesOHLCRequest {
	return &NullableGetEthCollectionSalesOHLCRequest{value: val, isSet: true}
}

func (v NullableGetEthCollectionSalesOHLCRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEthCollectionSalesOHLCRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


