/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetPolWashTradeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPolWashTradeRequest{}

// GetPolWashTradeRequest struct for GetPolWashTradeRequest
type GetPolWashTradeRequest struct {
	// The transaction hash to valildate.
	TransactionHash string `json:"transaction_hash"`
}

// NewGetPolWashTradeRequest instantiates a new GetPolWashTradeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPolWashTradeRequest(transactionHash string) *GetPolWashTradeRequest {
	this := GetPolWashTradeRequest{}
	this.TransactionHash = transactionHash
	return &this
}

// NewGetPolWashTradeRequestWithDefaults instantiates a new GetPolWashTradeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPolWashTradeRequestWithDefaults() *GetPolWashTradeRequest {
	this := GetPolWashTradeRequest{}
	return &this
}

// GetTransactionHash returns the TransactionHash field value
func (o *GetPolWashTradeRequest) GetTransactionHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionHash
}

// GetTransactionHashOk returns a tuple with the TransactionHash field value
// and a boolean to check if the value has been set.
func (o *GetPolWashTradeRequest) GetTransactionHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionHash, true
}

// SetTransactionHash sets field value
func (o *GetPolWashTradeRequest) SetTransactionHash(v string) {
	o.TransactionHash = v
}

func (o GetPolWashTradeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPolWashTradeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transaction_hash"] = o.TransactionHash
	return toSerialize, nil
}

type NullableGetPolWashTradeRequest struct {
	value *GetPolWashTradeRequest
	isSet bool
}

func (v NullableGetPolWashTradeRequest) Get() *GetPolWashTradeRequest {
	return v.value
}

func (v *NullableGetPolWashTradeRequest) Set(val *GetPolWashTradeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPolWashTradeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPolWashTradeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPolWashTradeRequest(val *GetPolWashTradeRequest) *NullableGetPolWashTradeRequest {
	return &NullableGetPolWashTradeRequest{value: val, isSet: true}
}

func (v NullableGetPolWashTradeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPolWashTradeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


