/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetSknMarketplaceDataRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSknMarketplaceDataRequest{}

// GetSknMarketplaceDataRequest struct for GetSknMarketplaceDataRequest
type GetSknMarketplaceDataRequest struct {
	// Array of collection addresses
	CollectionAddress []string `json:"collection_address"`
}

// NewGetSknMarketplaceDataRequest instantiates a new GetSknMarketplaceDataRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSknMarketplaceDataRequest(collectionAddress []string) *GetSknMarketplaceDataRequest {
	this := GetSknMarketplaceDataRequest{}
	this.CollectionAddress = collectionAddress
	return &this
}

// NewGetSknMarketplaceDataRequestWithDefaults instantiates a new GetSknMarketplaceDataRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSknMarketplaceDataRequestWithDefaults() *GetSknMarketplaceDataRequest {
	this := GetSknMarketplaceDataRequest{}
	return &this
}

// GetCollectionAddress returns the CollectionAddress field value
func (o *GetSknMarketplaceDataRequest) GetCollectionAddress() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.CollectionAddress
}

// GetCollectionAddressOk returns a tuple with the CollectionAddress field value
// and a boolean to check if the value has been set.
func (o *GetSknMarketplaceDataRequest) GetCollectionAddressOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CollectionAddress, true
}

// SetCollectionAddress sets field value
func (o *GetSknMarketplaceDataRequest) SetCollectionAddress(v []string) {
	o.CollectionAddress = v
}

func (o GetSknMarketplaceDataRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSknMarketplaceDataRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["collection_address"] = o.CollectionAddress
	return toSerialize, nil
}

type NullableGetSknMarketplaceDataRequest struct {
	value *GetSknMarketplaceDataRequest
	isSet bool
}

func (v NullableGetSknMarketplaceDataRequest) Get() *GetSknMarketplaceDataRequest {
	return v.value
}

func (v *NullableGetSknMarketplaceDataRequest) Set(val *GetSknMarketplaceDataRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSknMarketplaceDataRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSknMarketplaceDataRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSknMarketplaceDataRequest(val *GetSknMarketplaceDataRequest) *NullableGetSknMarketplaceDataRequest {
	return &NullableGetSknMarketplaceDataRequest{value: val, isSet: true}
}

func (v NullableGetSknMarketplaceDataRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSknMarketplaceDataRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


