/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetPolMarketplaceDataRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPolMarketplaceDataRequest{}

// GetPolMarketplaceDataRequest struct for GetPolMarketplaceDataRequest
type GetPolMarketplaceDataRequest struct {
	// Array of collection addresses
	CollectionAddress []string `json:"collection_address"`
}

// NewGetPolMarketplaceDataRequest instantiates a new GetPolMarketplaceDataRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPolMarketplaceDataRequest(collectionAddress []string) *GetPolMarketplaceDataRequest {
	this := GetPolMarketplaceDataRequest{}
	this.CollectionAddress = collectionAddress
	return &this
}

// NewGetPolMarketplaceDataRequestWithDefaults instantiates a new GetPolMarketplaceDataRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPolMarketplaceDataRequestWithDefaults() *GetPolMarketplaceDataRequest {
	this := GetPolMarketplaceDataRequest{}
	return &this
}

// GetCollectionAddress returns the CollectionAddress field value
func (o *GetPolMarketplaceDataRequest) GetCollectionAddress() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.CollectionAddress
}

// GetCollectionAddressOk returns a tuple with the CollectionAddress field value
// and a boolean to check if the value has been set.
func (o *GetPolMarketplaceDataRequest) GetCollectionAddressOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CollectionAddress, true
}

// SetCollectionAddress sets field value
func (o *GetPolMarketplaceDataRequest) SetCollectionAddress(v []string) {
	o.CollectionAddress = v
}

func (o GetPolMarketplaceDataRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPolMarketplaceDataRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["collection_address"] = o.CollectionAddress
	return toSerialize, nil
}

type NullableGetPolMarketplaceDataRequest struct {
	value *GetPolMarketplaceDataRequest
	isSet bool
}

func (v NullableGetPolMarketplaceDataRequest) Get() *GetPolMarketplaceDataRequest {
	return v.value
}

func (v *NullableGetPolMarketplaceDataRequest) Set(val *GetPolMarketplaceDataRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPolMarketplaceDataRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPolMarketplaceDataRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPolMarketplaceDataRequest(val *GetPolMarketplaceDataRequest) *NullableGetPolMarketplaceDataRequest {
	return &NullableGetPolMarketplaceDataRequest{value: val, isSet: true}
}

func (v NullableGetPolMarketplaceDataRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPolMarketplaceDataRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


