/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetPolWalletTransactionsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPolWalletTransactionsRequest{}

// GetPolWalletTransactionsRequest struct for GetPolWalletTransactionsRequest
type GetPolWalletTransactionsRequest struct {
	// The wallet address to search.
	WalletAddress *string `json:"wallet_address,omitempty"`
	// The pagination cursor.
	Page *int32 `json:"page,omitempty"`
	// The number of records returned per page.
	PageSize *int32 `json:"page_size,omitempty"`
}

// NewGetPolWalletTransactionsRequest instantiates a new GetPolWalletTransactionsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPolWalletTransactionsRequest() *GetPolWalletTransactionsRequest {
	this := GetPolWalletTransactionsRequest{}
	return &this
}

// NewGetPolWalletTransactionsRequestWithDefaults instantiates a new GetPolWalletTransactionsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPolWalletTransactionsRequestWithDefaults() *GetPolWalletTransactionsRequest {
	this := GetPolWalletTransactionsRequest{}
	return &this
}

// GetWalletAddress returns the WalletAddress field value if set, zero value otherwise.
func (o *GetPolWalletTransactionsRequest) GetWalletAddress() string {
	if o == nil || isNil(o.WalletAddress) {
		var ret string
		return ret
	}
	return *o.WalletAddress
}

// GetWalletAddressOk returns a tuple with the WalletAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPolWalletTransactionsRequest) GetWalletAddressOk() (*string, bool) {
	if o == nil || isNil(o.WalletAddress) {
		return nil, false
	}
	return o.WalletAddress, true
}

// HasWalletAddress returns a boolean if a field has been set.
func (o *GetPolWalletTransactionsRequest) HasWalletAddress() bool {
	if o != nil && !isNil(o.WalletAddress) {
		return true
	}

	return false
}

// SetWalletAddress gets a reference to the given string and assigns it to the WalletAddress field.
func (o *GetPolWalletTransactionsRequest) SetWalletAddress(v string) {
	o.WalletAddress = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *GetPolWalletTransactionsRequest) GetPage() int32 {
	if o == nil || isNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPolWalletTransactionsRequest) GetPageOk() (*int32, bool) {
	if o == nil || isNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *GetPolWalletTransactionsRequest) HasPage() bool {
	if o != nil && !isNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *GetPolWalletTransactionsRequest) SetPage(v int32) {
	o.Page = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *GetPolWalletTransactionsRequest) GetPageSize() int32 {
	if o == nil || isNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPolWalletTransactionsRequest) GetPageSizeOk() (*int32, bool) {
	if o == nil || isNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *GetPolWalletTransactionsRequest) HasPageSize() bool {
	if o != nil && !isNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *GetPolWalletTransactionsRequest) SetPageSize(v int32) {
	o.PageSize = &v
}

func (o GetPolWalletTransactionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPolWalletTransactionsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.WalletAddress) {
		toSerialize["wallet_address"] = o.WalletAddress
	}
	if !isNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !isNil(o.PageSize) {
		toSerialize["page_size"] = o.PageSize
	}
	return toSerialize, nil
}

type NullableGetPolWalletTransactionsRequest struct {
	value *GetPolWalletTransactionsRequest
	isSet bool
}

func (v NullableGetPolWalletTransactionsRequest) Get() *GetPolWalletTransactionsRequest {
	return v.value
}

func (v *NullableGetPolWalletTransactionsRequest) Set(val *GetPolWalletTransactionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPolWalletTransactionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPolWalletTransactionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPolWalletTransactionsRequest(val *GetPolWalletTransactionsRequest) *NullableGetPolWalletTransactionsRequest {
	return &NullableGetPolWalletTransactionsRequest{value: val, isSet: true}
}

func (v NullableGetPolWalletTransactionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPolWalletTransactionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


