/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetEthTokenSummaryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEthTokenSummaryRequest{}

// GetEthTokenSummaryRequest struct for GetEthTokenSummaryRequest
type GetEthTokenSummaryRequest struct {
	// The contract address of the token collection.
	CollectionAddress string `json:"collection_address"`
	// The id for the token.
	TokenId []string `json:"token_id"`
	// The start date to pull data for calculations
	StartDate *string `json:"start_date,omitempty"`
	// The end date to pull data for calculations
	EndDate *string `json:"end_date,omitempty"`
	// The currency to report results in
	ReptCurr *string `json:"rept_curr,omitempty"`
	// Exclude suspected wash transactions?
	ExcludeWash *bool `json:"exclude_wash,omitempty"`
}

// NewGetEthTokenSummaryRequest instantiates a new GetEthTokenSummaryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEthTokenSummaryRequest(collectionAddress string, tokenId []string) *GetEthTokenSummaryRequest {
	this := GetEthTokenSummaryRequest{}
	this.CollectionAddress = collectionAddress
	this.TokenId = tokenId
	return &this
}

// NewGetEthTokenSummaryRequestWithDefaults instantiates a new GetEthTokenSummaryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEthTokenSummaryRequestWithDefaults() *GetEthTokenSummaryRequest {
	this := GetEthTokenSummaryRequest{}
	return &this
}

// GetCollectionAddress returns the CollectionAddress field value
func (o *GetEthTokenSummaryRequest) GetCollectionAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CollectionAddress
}

// GetCollectionAddressOk returns a tuple with the CollectionAddress field value
// and a boolean to check if the value has been set.
func (o *GetEthTokenSummaryRequest) GetCollectionAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CollectionAddress, true
}

// SetCollectionAddress sets field value
func (o *GetEthTokenSummaryRequest) SetCollectionAddress(v string) {
	o.CollectionAddress = v
}

// GetTokenId returns the TokenId field value
func (o *GetEthTokenSummaryRequest) GetTokenId() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *GetEthTokenSummaryRequest) GetTokenIdOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TokenId, true
}

// SetTokenId sets field value
func (o *GetEthTokenSummaryRequest) SetTokenId(v []string) {
	o.TokenId = v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *GetEthTokenSummaryRequest) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthTokenSummaryRequest) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *GetEthTokenSummaryRequest) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *GetEthTokenSummaryRequest) SetStartDate(v string) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *GetEthTokenSummaryRequest) GetEndDate() string {
	if o == nil || IsNil(o.EndDate) {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthTokenSummaryRequest) GetEndDateOk() (*string, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *GetEthTokenSummaryRequest) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *GetEthTokenSummaryRequest) SetEndDate(v string) {
	o.EndDate = &v
}

// GetReptCurr returns the ReptCurr field value if set, zero value otherwise.
func (o *GetEthTokenSummaryRequest) GetReptCurr() string {
	if o == nil || IsNil(o.ReptCurr) {
		var ret string
		return ret
	}
	return *o.ReptCurr
}

// GetReptCurrOk returns a tuple with the ReptCurr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthTokenSummaryRequest) GetReptCurrOk() (*string, bool) {
	if o == nil || IsNil(o.ReptCurr) {
		return nil, false
	}
	return o.ReptCurr, true
}

// HasReptCurr returns a boolean if a field has been set.
func (o *GetEthTokenSummaryRequest) HasReptCurr() bool {
	if o != nil && !IsNil(o.ReptCurr) {
		return true
	}

	return false
}

// SetReptCurr gets a reference to the given string and assigns it to the ReptCurr field.
func (o *GetEthTokenSummaryRequest) SetReptCurr(v string) {
	o.ReptCurr = &v
}

// GetExcludeWash returns the ExcludeWash field value if set, zero value otherwise.
func (o *GetEthTokenSummaryRequest) GetExcludeWash() bool {
	if o == nil || IsNil(o.ExcludeWash) {
		var ret bool
		return ret
	}
	return *o.ExcludeWash
}

// GetExcludeWashOk returns a tuple with the ExcludeWash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthTokenSummaryRequest) GetExcludeWashOk() (*bool, bool) {
	if o == nil || IsNil(o.ExcludeWash) {
		return nil, false
	}
	return o.ExcludeWash, true
}

// HasExcludeWash returns a boolean if a field has been set.
func (o *GetEthTokenSummaryRequest) HasExcludeWash() bool {
	if o != nil && !IsNil(o.ExcludeWash) {
		return true
	}

	return false
}

// SetExcludeWash gets a reference to the given bool and assigns it to the ExcludeWash field.
func (o *GetEthTokenSummaryRequest) SetExcludeWash(v bool) {
	o.ExcludeWash = &v
}

func (o GetEthTokenSummaryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEthTokenSummaryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["collection_address"] = o.CollectionAddress
	toSerialize["token_id"] = o.TokenId
	if !IsNil(o.StartDate) {
		toSerialize["start_date"] = o.StartDate
	}
	if !IsNil(o.EndDate) {
		toSerialize["end_date"] = o.EndDate
	}
	if !IsNil(o.ReptCurr) {
		toSerialize["rept_curr"] = o.ReptCurr
	}
	if !IsNil(o.ExcludeWash) {
		toSerialize["exclude_wash"] = o.ExcludeWash
	}
	return toSerialize, nil
}

type NullableGetEthTokenSummaryRequest struct {
	value *GetEthTokenSummaryRequest
	isSet bool
}

func (v NullableGetEthTokenSummaryRequest) Get() *GetEthTokenSummaryRequest {
	return v.value
}

func (v *NullableGetEthTokenSummaryRequest) Set(val *GetEthTokenSummaryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEthTokenSummaryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEthTokenSummaryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEthTokenSummaryRequest(val *GetEthTokenSummaryRequest) *NullableGetEthTokenSummaryRequest {
	return &NullableGetEthTokenSummaryRequest{value: val, isSet: true}
}

func (v NullableGetEthTokenSummaryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEthTokenSummaryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


