/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetPolCollectionSalesOHLCRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPolCollectionSalesOHLCRequest{}

// GetPolCollectionSalesOHLCRequest struct for GetPolCollectionSalesOHLCRequest
type GetPolCollectionSalesOHLCRequest struct {
	// The Polygon contract address to identify the collection.
	CollectionAddress string `json:"collection_address"`
	// The interval at which to return OHLC, e.g. `1D` for daily, `1M` for monthly etc.
	Frequency *string `json:"frequency,omitempty"`
	// An attribute of the NFT to group results by.
	GroupBy *string `json:"group_by,omitempty"`
	// If 'true', response dicts contain OHLCV
	Volume *bool `json:"volume,omitempty"`
	// If 'true', append number of trades to OHLC(V)
	NTrades *bool `json:"n_trades,omitempty"`
	// The currency to report results in
	ReptCurr *string `json:"rept_curr,omitempty"`
	// The start date to pull data for calculations
	StartDate *string `json:"start_date,omitempty"`
	// The end date to pull data for calculations
	EndDate *string `json:"end_date,omitempty"`
	// Exclude suspected wash transactions?
	ExcludeWash *bool `json:"exclude_wash,omitempty"`
}

// NewGetPolCollectionSalesOHLCRequest instantiates a new GetPolCollectionSalesOHLCRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPolCollectionSalesOHLCRequest(collectionAddress string) *GetPolCollectionSalesOHLCRequest {
	this := GetPolCollectionSalesOHLCRequest{}
	this.CollectionAddress = collectionAddress
	return &this
}

// NewGetPolCollectionSalesOHLCRequestWithDefaults instantiates a new GetPolCollectionSalesOHLCRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPolCollectionSalesOHLCRequestWithDefaults() *GetPolCollectionSalesOHLCRequest {
	this := GetPolCollectionSalesOHLCRequest{}
	return &this
}

// GetCollectionAddress returns the CollectionAddress field value
func (o *GetPolCollectionSalesOHLCRequest) GetCollectionAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CollectionAddress
}

// GetCollectionAddressOk returns a tuple with the CollectionAddress field value
// and a boolean to check if the value has been set.
func (o *GetPolCollectionSalesOHLCRequest) GetCollectionAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CollectionAddress, true
}

// SetCollectionAddress sets field value
func (o *GetPolCollectionSalesOHLCRequest) SetCollectionAddress(v string) {
	o.CollectionAddress = v
}

// GetFrequency returns the Frequency field value if set, zero value otherwise.
func (o *GetPolCollectionSalesOHLCRequest) GetFrequency() string {
	if o == nil || isNil(o.Frequency) {
		var ret string
		return ret
	}
	return *o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPolCollectionSalesOHLCRequest) GetFrequencyOk() (*string, bool) {
	if o == nil || isNil(o.Frequency) {
		return nil, false
	}
	return o.Frequency, true
}

// HasFrequency returns a boolean if a field has been set.
func (o *GetPolCollectionSalesOHLCRequest) HasFrequency() bool {
	if o != nil && !isNil(o.Frequency) {
		return true
	}

	return false
}

// SetFrequency gets a reference to the given string and assigns it to the Frequency field.
func (o *GetPolCollectionSalesOHLCRequest) SetFrequency(v string) {
	o.Frequency = &v
}

// GetGroupBy returns the GroupBy field value if set, zero value otherwise.
func (o *GetPolCollectionSalesOHLCRequest) GetGroupBy() string {
	if o == nil || isNil(o.GroupBy) {
		var ret string
		return ret
	}
	return *o.GroupBy
}

// GetGroupByOk returns a tuple with the GroupBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPolCollectionSalesOHLCRequest) GetGroupByOk() (*string, bool) {
	if o == nil || isNil(o.GroupBy) {
		return nil, false
	}
	return o.GroupBy, true
}

// HasGroupBy returns a boolean if a field has been set.
func (o *GetPolCollectionSalesOHLCRequest) HasGroupBy() bool {
	if o != nil && !isNil(o.GroupBy) {
		return true
	}

	return false
}

// SetGroupBy gets a reference to the given string and assigns it to the GroupBy field.
func (o *GetPolCollectionSalesOHLCRequest) SetGroupBy(v string) {
	o.GroupBy = &v
}

// GetVolume returns the Volume field value if set, zero value otherwise.
func (o *GetPolCollectionSalesOHLCRequest) GetVolume() bool {
	if o == nil || isNil(o.Volume) {
		var ret bool
		return ret
	}
	return *o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPolCollectionSalesOHLCRequest) GetVolumeOk() (*bool, bool) {
	if o == nil || isNil(o.Volume) {
		return nil, false
	}
	return o.Volume, true
}

// HasVolume returns a boolean if a field has been set.
func (o *GetPolCollectionSalesOHLCRequest) HasVolume() bool {
	if o != nil && !isNil(o.Volume) {
		return true
	}

	return false
}

// SetVolume gets a reference to the given bool and assigns it to the Volume field.
func (o *GetPolCollectionSalesOHLCRequest) SetVolume(v bool) {
	o.Volume = &v
}

// GetNTrades returns the NTrades field value if set, zero value otherwise.
func (o *GetPolCollectionSalesOHLCRequest) GetNTrades() bool {
	if o == nil || isNil(o.NTrades) {
		var ret bool
		return ret
	}
	return *o.NTrades
}

// GetNTradesOk returns a tuple with the NTrades field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPolCollectionSalesOHLCRequest) GetNTradesOk() (*bool, bool) {
	if o == nil || isNil(o.NTrades) {
		return nil, false
	}
	return o.NTrades, true
}

// HasNTrades returns a boolean if a field has been set.
func (o *GetPolCollectionSalesOHLCRequest) HasNTrades() bool {
	if o != nil && !isNil(o.NTrades) {
		return true
	}

	return false
}

// SetNTrades gets a reference to the given bool and assigns it to the NTrades field.
func (o *GetPolCollectionSalesOHLCRequest) SetNTrades(v bool) {
	o.NTrades = &v
}

// GetReptCurr returns the ReptCurr field value if set, zero value otherwise.
func (o *GetPolCollectionSalesOHLCRequest) GetReptCurr() string {
	if o == nil || isNil(o.ReptCurr) {
		var ret string
		return ret
	}
	return *o.ReptCurr
}

// GetReptCurrOk returns a tuple with the ReptCurr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPolCollectionSalesOHLCRequest) GetReptCurrOk() (*string, bool) {
	if o == nil || isNil(o.ReptCurr) {
		return nil, false
	}
	return o.ReptCurr, true
}

// HasReptCurr returns a boolean if a field has been set.
func (o *GetPolCollectionSalesOHLCRequest) HasReptCurr() bool {
	if o != nil && !isNil(o.ReptCurr) {
		return true
	}

	return false
}

// SetReptCurr gets a reference to the given string and assigns it to the ReptCurr field.
func (o *GetPolCollectionSalesOHLCRequest) SetReptCurr(v string) {
	o.ReptCurr = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *GetPolCollectionSalesOHLCRequest) GetStartDate() string {
	if o == nil || isNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPolCollectionSalesOHLCRequest) GetStartDateOk() (*string, bool) {
	if o == nil || isNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *GetPolCollectionSalesOHLCRequest) HasStartDate() bool {
	if o != nil && !isNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *GetPolCollectionSalesOHLCRequest) SetStartDate(v string) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *GetPolCollectionSalesOHLCRequest) GetEndDate() string {
	if o == nil || isNil(o.EndDate) {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPolCollectionSalesOHLCRequest) GetEndDateOk() (*string, bool) {
	if o == nil || isNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *GetPolCollectionSalesOHLCRequest) HasEndDate() bool {
	if o != nil && !isNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *GetPolCollectionSalesOHLCRequest) SetEndDate(v string) {
	o.EndDate = &v
}

// GetExcludeWash returns the ExcludeWash field value if set, zero value otherwise.
func (o *GetPolCollectionSalesOHLCRequest) GetExcludeWash() bool {
	if o == nil || isNil(o.ExcludeWash) {
		var ret bool
		return ret
	}
	return *o.ExcludeWash
}

// GetExcludeWashOk returns a tuple with the ExcludeWash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPolCollectionSalesOHLCRequest) GetExcludeWashOk() (*bool, bool) {
	if o == nil || isNil(o.ExcludeWash) {
		return nil, false
	}
	return o.ExcludeWash, true
}

// HasExcludeWash returns a boolean if a field has been set.
func (o *GetPolCollectionSalesOHLCRequest) HasExcludeWash() bool {
	if o != nil && !isNil(o.ExcludeWash) {
		return true
	}

	return false
}

// SetExcludeWash gets a reference to the given bool and assigns it to the ExcludeWash field.
func (o *GetPolCollectionSalesOHLCRequest) SetExcludeWash(v bool) {
	o.ExcludeWash = &v
}

func (o GetPolCollectionSalesOHLCRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPolCollectionSalesOHLCRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["collection_address"] = o.CollectionAddress
	if !isNil(o.Frequency) {
		toSerialize["frequency"] = o.Frequency
	}
	if !isNil(o.GroupBy) {
		toSerialize["group_by"] = o.GroupBy
	}
	if !isNil(o.Volume) {
		toSerialize["volume"] = o.Volume
	}
	if !isNil(o.NTrades) {
		toSerialize["n_trades"] = o.NTrades
	}
	if !isNil(o.ReptCurr) {
		toSerialize["rept_curr"] = o.ReptCurr
	}
	if !isNil(o.StartDate) {
		toSerialize["start_date"] = o.StartDate
	}
	if !isNil(o.EndDate) {
		toSerialize["end_date"] = o.EndDate
	}
	if !isNil(o.ExcludeWash) {
		toSerialize["exclude_wash"] = o.ExcludeWash
	}
	return toSerialize, nil
}

type NullableGetPolCollectionSalesOHLCRequest struct {
	value *GetPolCollectionSalesOHLCRequest
	isSet bool
}

func (v NullableGetPolCollectionSalesOHLCRequest) Get() *GetPolCollectionSalesOHLCRequest {
	return v.value
}

func (v *NullableGetPolCollectionSalesOHLCRequest) Set(val *GetPolCollectionSalesOHLCRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPolCollectionSalesOHLCRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPolCollectionSalesOHLCRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPolCollectionSalesOHLCRequest(val *GetPolCollectionSalesOHLCRequest) *NullableGetPolCollectionSalesOHLCRequest {
	return &NullableGetPolCollectionSalesOHLCRequest{value: val, isSet: true}
}

func (v NullableGetPolCollectionSalesOHLCRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPolCollectionSalesOHLCRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


