/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetEthWashTradeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEthWashTradeRequest{}

// GetEthWashTradeRequest struct for GetEthWashTradeRequest
type GetEthWashTradeRequest struct {
	// The transaction hash to valildate.
	TransactionHash string `json:"transaction_hash"`
}

// NewGetEthWashTradeRequest instantiates a new GetEthWashTradeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEthWashTradeRequest(transactionHash string) *GetEthWashTradeRequest {
	this := GetEthWashTradeRequest{}
	this.TransactionHash = transactionHash
	return &this
}

// NewGetEthWashTradeRequestWithDefaults instantiates a new GetEthWashTradeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEthWashTradeRequestWithDefaults() *GetEthWashTradeRequest {
	this := GetEthWashTradeRequest{}
	return &this
}

// GetTransactionHash returns the TransactionHash field value
func (o *GetEthWashTradeRequest) GetTransactionHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionHash
}

// GetTransactionHashOk returns a tuple with the TransactionHash field value
// and a boolean to check if the value has been set.
func (o *GetEthWashTradeRequest) GetTransactionHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionHash, true
}

// SetTransactionHash sets field value
func (o *GetEthWashTradeRequest) SetTransactionHash(v string) {
	o.TransactionHash = v
}

func (o GetEthWashTradeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEthWashTradeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transaction_hash"] = o.TransactionHash
	return toSerialize, nil
}

type NullableGetEthWashTradeRequest struct {
	value *GetEthWashTradeRequest
	isSet bool
}

func (v NullableGetEthWashTradeRequest) Get() *GetEthWashTradeRequest {
	return v.value
}

func (v *NullableGetEthWashTradeRequest) Set(val *GetEthWashTradeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEthWashTradeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEthWashTradeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEthWashTradeRequest(val *GetEthWashTradeRequest) *NullableGetEthWashTradeRequest {
	return &NullableGetEthWashTradeRequest{value: val, isSet: true}
}

func (v NullableGetEthWashTradeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEthWashTradeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


