/*
Gallop API

Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.

API version: 1.0.0
Contact: support@higallop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetSknMarketplaceFloorPriceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSknMarketplaceFloorPriceRequest{}

// GetSknMarketplaceFloorPriceRequest struct for GetSknMarketplaceFloorPriceRequest
type GetSknMarketplaceFloorPriceRequest struct {
	// The pagination cursor.
	Page *int32 `json:"page,omitempty"`
	// The number of records returned per page.
	PageSize *int32 `json:"page_size,omitempty"`
	// Array of collection addresses
	CollectionAddress []string `json:"collection_address,omitempty"`
}

// NewGetSknMarketplaceFloorPriceRequest instantiates a new GetSknMarketplaceFloorPriceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSknMarketplaceFloorPriceRequest() *GetSknMarketplaceFloorPriceRequest {
	this := GetSknMarketplaceFloorPriceRequest{}
	return &this
}

// NewGetSknMarketplaceFloorPriceRequestWithDefaults instantiates a new GetSknMarketplaceFloorPriceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSknMarketplaceFloorPriceRequestWithDefaults() *GetSknMarketplaceFloorPriceRequest {
	this := GetSknMarketplaceFloorPriceRequest{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *GetSknMarketplaceFloorPriceRequest) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSknMarketplaceFloorPriceRequest) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *GetSknMarketplaceFloorPriceRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *GetSknMarketplaceFloorPriceRequest) SetPage(v int32) {
	o.Page = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *GetSknMarketplaceFloorPriceRequest) GetPageSize() int32 {
	if o == nil || IsNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSknMarketplaceFloorPriceRequest) GetPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *GetSknMarketplaceFloorPriceRequest) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *GetSknMarketplaceFloorPriceRequest) SetPageSize(v int32) {
	o.PageSize = &v
}

// GetCollectionAddress returns the CollectionAddress field value if set, zero value otherwise.
func (o *GetSknMarketplaceFloorPriceRequest) GetCollectionAddress() []string {
	if o == nil || IsNil(o.CollectionAddress) {
		var ret []string
		return ret
	}
	return o.CollectionAddress
}

// GetCollectionAddressOk returns a tuple with the CollectionAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSknMarketplaceFloorPriceRequest) GetCollectionAddressOk() ([]string, bool) {
	if o == nil || IsNil(o.CollectionAddress) {
		return nil, false
	}
	return o.CollectionAddress, true
}

// HasCollectionAddress returns a boolean if a field has been set.
func (o *GetSknMarketplaceFloorPriceRequest) HasCollectionAddress() bool {
	if o != nil && !IsNil(o.CollectionAddress) {
		return true
	}

	return false
}

// SetCollectionAddress gets a reference to the given []string and assigns it to the CollectionAddress field.
func (o *GetSknMarketplaceFloorPriceRequest) SetCollectionAddress(v []string) {
	o.CollectionAddress = v
}

func (o GetSknMarketplaceFloorPriceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSknMarketplaceFloorPriceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PageSize) {
		toSerialize["page_size"] = o.PageSize
	}
	if !IsNil(o.CollectionAddress) {
		toSerialize["collection_address"] = o.CollectionAddress
	}
	return toSerialize, nil
}

type NullableGetSknMarketplaceFloorPriceRequest struct {
	value *GetSknMarketplaceFloorPriceRequest
	isSet bool
}

func (v NullableGetSknMarketplaceFloorPriceRequest) Get() *GetSknMarketplaceFloorPriceRequest {
	return v.value
}

func (v *NullableGetSknMarketplaceFloorPriceRequest) Set(val *GetSknMarketplaceFloorPriceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSknMarketplaceFloorPriceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSknMarketplaceFloorPriceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSknMarketplaceFloorPriceRequest(val *GetSknMarketplaceFloorPriceRequest) *NullableGetSknMarketplaceFloorPriceRequest {
	return &NullableGetSknMarketplaceFloorPriceRequest{value: val, isSet: true}
}

func (v NullableGetSknMarketplaceFloorPriceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSknMarketplaceFloorPriceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


